FROM node:8.2.1

MAINTAINER Alvaro Vilanova Vidal <alvaro@thebookofeveryone.com>

RUN npm install -g elm@0.18.0
RUN npm install -g elm-test@0.18.7
RUN npm install -g elm-analyse@0.18.7

ENTRYPOINT ["elm"]

